# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VNNetWorking' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for VNNetWorking
  pod 'AFNetworking', '~> 3.2.1'
  pod "HandyFrame"
  pod "CTNetworking"
  target 'VNNetWorkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
